FROM pytorch/pytorch:2.7.1-cuda12.8-cudnn9-runtime

RUN pip install --upgrade pip && \
    apt update -y && \
    apt install -y --no-install-recommends \
    build-essential \
    g++ \
    libsndfile1 \
    libportaudio2 \
    curl \
    ffmpeg \
    portaudio19-dev \
    && apt clean && \
    rm -rf /var/lib/apt/lists/*

ENV WHISPER_MODEL="tiny"
ENV DEVICE="cpu"

WORKDIR /app

ENV PYTHONPATH="${PYTHONPATH}:/app"
RUN export PYTHONPATH="${PYTHONPATH}:/app"

COPY requirements.txt /app/requirements.txt
RUN pip3 install -r /app/requirements.txt

COPY RealtimeSTT /app/RealtimeSTT
COPY RealtimeSTT_server /app/RealtimeSTT_server

EXPOSE 8011
EXPOSE 8012

CMD ["python3", "RealtimeSTT_server/stt_server.py","-m ${WHISPER_MODEL} -r ${WHISPER_MODEL} -l ru --device ${DEVICE}"]
